name: ofnotes

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.14"

      - name: Restore Npm Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Check Code style
        run: npm run format:check

      - name: Run Tests
        run: npm run test -- --watchAll=false --coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.3
        if: ${{ !contains(github.actor, 'dependabot') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        if: ${{ !contains(github.actor, 'dependabot') }}
        run: |
          npm i -g netlify-cli
          netlify build

      - name: Deploy Preview to Netlify
        if: ${{ !contains(github.actor, 'dependabot') && github.event_name == 'pull_request' }}
        run: netlify deploy --dir=./public

      - name: Deploy Prod to Netlify
        if: ${{ !contains(github.actor, 'dependabot') && github.event_name == 'push' }}
        run: netlify deploy --dir=./public --prod
